ktor:
    application:
        modules:
            - com.schlepping.arcana.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "secret"

database:
  url: "jdbc:postgresql://localhost:5435/arcana"
  user: "arcana"
  password: "arcana_dev"