ktor:
    application:
        modules:
            - com.schlepping.arcana.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    secret: "change-me-in-production"
    issuer: "arcana-server"
    audience: "arcana-app"
    realm: "arcana"
    accessTokenExpireMin: 15
    refreshTokenExpireDays: 30

database:
  url: "jdbc:postgresql://localhost:5435/arcana"
  user: "arcana"
  password: "arcana_dev"